/* Generated By:JavaCC: Do not edit this line. CalcLogicConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalcLogicConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OR = 4;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int FALSO = 6;
  /** RegularExpression Id. */
  int VERDADEIRO = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"+\"",
    "\".\"",
    "<FALSO>",
    "<VERDADEIRO>",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
  };

}
