/* Generated By:JavaCC: Do not edit this line. CalcConjuntosConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalcConjuntosConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int UNION = 5;
  /** RegularExpression Id. */
  int INTERSECT = 6;
  /** RegularExpression Id. */
  int CONTIDO = 7;
  /** RegularExpression Id. */
  int PERTENCE = 8;
  /** RegularExpression Id. */
  int SEQ = 9;
  /** RegularExpression Id. */
  int ATRIB = 10;
  /** RegularExpression Id. */
  int ABRECH = 11;
  /** RegularExpression Id. */
  int FECHACH = 12;
  /** RegularExpression Id. */
  int ABREPAR = 13;
  /** RegularExpression Id. */
  int FECHAPAR = 14;
  /** RegularExpression Id. */
  int PNT_VIRG = 15;
  /** RegularExpression Id. */
  int VIRG = 16;
  /** RegularExpression Id. */
  int NUMERIC = 17;
  /** RegularExpression Id. */
  int VAR = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int LETTERS = 20;
  /** RegularExpression Id. */
  int STRING = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"U\"",
    "\"^\"",
    "\"c\"",
    "\"E\"",
    "\"...\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "<NUMERIC>",
    "<VAR>",
    "<DIGIT>",
    "<LETTERS>",
    "<STRING>",
  };

}
