/* Generated By:JavaCC: Do not edit this line. CalcRomanoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalcRomanoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIBE = 5;
  /** RegularExpression Id. */
  int IDENT = 6;
  /** RegularExpression Id. */
  int ATRIB = 7;
  /** RegularExpression Id. */
  int ADICAO = 8;
  /** RegularExpression Id. */
  int PT_VIRG = 9;
  /** RegularExpression Id. */
  int NUM_ARAB = 10;
  /** RegularExpression Id. */
  int NUM_ROMANO = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"exibe\"",
    "<IDENT>",
    "\":=\"",
    "\"+\"",
    "\";\"",
    "<NUM_ARAB>",
    "<NUM_ROMANO>",
  };

}
