/* Generated By:JavaCC: Do not edit this line. Exercicio2Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Exercicio2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EX1A = 5;
  /** RegularExpression Id. */
  int String = 6;
  /** RegularExpression Id. */
  int NUM = 7;
  /** RegularExpression Id. */
  int ROMANO = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<EX1A>",
    "<String>",
    "<NUM>",
    "<ROMANO>",
  };

}
