/* Generated By:JavaCC: Do not edit this line. JavaCPascalConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaCPascalConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int REAL = 5;
  /** RegularExpression Id. */
  int OPER_REL_JAVA_C_PASCAL = 6;
  /** RegularExpression Id. */
  int OPER_REL_JAVA_C = 7;
  /** RegularExpression Id. */
  int OPER_REL_PASCAL = 8;
  /** RegularExpression Id. */
  int OPER_LOG_JAVA_C = 9;
  /** RegularExpression Id. */
  int OPER_LOG_PASCAL = 10;
  /** RegularExpression Id. */
  int HEX = 11;
  /** RegularExpression Id. */
  int ABRE_PAR = 12;
  /** RegularExpression Id. */
  int FECHA_PAR = 13;
  /** RegularExpression Id. */
  int VAR = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<REAL>",
    "<OPER_REL_JAVA_C_PASCAL>",
    "<OPER_REL_JAVA_C>",
    "<OPER_REL_PASCAL>",
    "<OPER_LOG_JAVA_C>",
    "<OPER_LOG_PASCAL>",
    "<HEX>",
    "\"(\"",
    "\")\"",
    "<VAR>",
  };

}
