/* Generated By:JavaCC: Do not edit this line. ZelLexicoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ZelLexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIBE = 8;
  /** RegularExpression Id. */
  int TAB = 9;
  /** RegularExpression Id. */
  int EOL = 10;
  /** RegularExpression Id. */
  int PNTVIRG = 11;
  /** RegularExpression Id. */
  int VAR = 12;
  /** RegularExpression Id. */
  int VAR_DCL = 13;
  /** RegularExpression Id. */
  int TP_STRING = 14;
  /** RegularExpression Id. */
  int TP_REAL = 15;
  /** RegularExpression Id. */
  int TP_INT = 16;
  /** RegularExpression Id. */
  int TP_CHAR = 17;
  /** RegularExpression Id. */
  int TP_LIST = 18;
  /** RegularExpression Id. */
  int DOISP = 19;
  /** RegularExpression Id. */
  int ATRIB = 20;
  /** RegularExpression Id. */
  int NUM_REAL = 21;
  /** RegularExpression Id. */
  int NUM_INT = 22;
  /** RegularExpression Id. */
  int VIRG = 23;
  /** RegularExpression Id. */
  int ABRECH = 24;
  /** RegularExpression Id. */
  int FECHACH = 25;
  /** RegularExpression Id. */
  int ABREPAR = 26;
  /** RegularExpression Id. */
  int FECHAPAR = 27;
  /** RegularExpression Id. */
  int ARROBA = 28;
  /** RegularExpression Id. */
  int DOLLAR = 29;
  /** RegularExpression Id. */
  int IF = 30;
  /** RegularExpression Id. */
  int FI = 31;
  /** RegularExpression Id. */
  int ELSE = 32;
  /** RegularExpression Id. */
  int IN = 33;
  /** RegularExpression Id. */
  int TO = 34;
  /** RegularExpression Id. */
  int STEP = 35;
  /** RegularExpression Id. */
  int FOREACH = 36;
  /** RegularExpression Id. */
  int WHILE = 37;
  /** RegularExpression Id. */
  int END = 38;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int comentario1 = 1;
  /** Lexical state. */
  int comentario2 = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"!!\"",
    "<token of kind 4>",
    "\"!#\"",
    "\"#!\"",
    "<token of kind 7>",
    "\"exibe\"",
    "\"\\t\"",
    "\"\\n\"",
    "\";\"",
    "<VAR>",
    "\"vars\"",
    "\"string\"",
    "\"real\"",
    "\"int\"",
    "\"char\"",
    "\"list\"",
    "\":\"",
    "\"=\"",
    "<NUM_REAL>",
    "<NUM_INT>",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"@\"",
    "\"$\"",
    "\"if\"",
    "\"fi\"",
    "\"else\"",
    "\"in\"",
    "\"to\"",
    "\"step\"",
    "\"foreach\"",
    "\"while\"",
    "\"end\"",
  };

}
